import re
from typing import Dict, Tuple

FINANCIAL_DISCLAIMER = (
    "\n\n---\n"
    "⚠️ **Compliance Disclaimer:** *This report and analysis are generated by an AI Agentic system for informational and research purposes only. "
    "It does not constitute financial advice, investment endorsement, or an offer to buy/sell securities. Consult a certified financial advisor before investing.*"
)

def sanitize_input(query: str) -> Tuple[str, bool]:
    """
    Sanitizes user input to prevent prompt injections and malicious queries.
    Returns (cleaned_query, is_safe).
    """
    injection_patterns = [
        r"ignore previous instructions",
        r"system prompt",
        r"override system instructions",
        r"jailbreak"
    ]
    query_lower = query.lower()
    for pattern in injection_patterns:
        if re.search(pattern, query_lower):
            return "Sanitized Query: Provide company research.", False
            
    return query.strip(), True

def append_guardrail_disclaimer(response_text: str) -> str:
    """
    Appends mandatory SEC/FINRA compliance financial disclaimer.
    """
    if "Compliance Disclaimer" not in response_text:
        return response_text + FINANCIAL_DISCLAIMER
    return response_text

def calculate_token_cost(prompt_length: int, response_length: int, provider: str = "groq") -> Dict[str, float]:
    """
    Estimates token counts and LLM API cost metrics for observability.
    """
    # Rough approximation: 1 token ~ 4 characters
    est_prompt_tokens = max(1, prompt_length // 4)
    est_completion_tokens = max(1, response_length // 4)
    total_tokens = est_prompt_tokens + est_completion_tokens
    
    # Cost per 1K tokens (approximate)
    cost_per_1k = 0.0005 if provider == "groq" else 0.0015
    total_cost = (total_tokens / 1000.0) * cost_per_1k
    
    return {
        "prompt_tokens": est_prompt_tokens,
        "completion_tokens": est_completion_tokens,
        "total_tokens": total_tokens,
        "estimated_cost_usd": round(total_cost, 6)
    }
